services:
  chat:
    build: .
    env_file: .env
    volumes:
      - ./srcs:/app/srcs
    ports:
      - ${PORT}:3000
    command: ["uvicorn", "srcs.main:app", "--reload", "--host=0.0.0.0", "--port=3000"]
