services:
  chat:
    build: chat-server
    restart: always
    env_file: .env
    volumes:
      - ./chat-server:/app/srcs
      - ./conversation:/conversation
      - ./logs:/logs
    ports:
      - ${PORT}:3000
    command: [ "uvicorn", "main:app", "--reload", "--host=0.0.0.0", "--port=3000" ]
    profiles:
      - all
      - chat

  recommendation:
    build: recommendation
    restart: always
    env_file: .env
    ports:
      - ${REC_PORT}:3000
    volumes:
      - ./recommendation:/app/srcs
      - ./logs:/logs
    command: [ "uvicorn", "main:app", "--reload", "--host=0.0.0.0", "--port=3000" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    profiles:
      - all
      - recommendation

  summary:
    build: summary
    restart: always
    env_file: .env
    volumes:
      - ./summary:/app/srcs
      - ./conversation:/conversation
      - ./logs:/logs
    ports:
      - ${SUM_PORT}:3000
    command: [ "uvicorn", "main:app", "--reload", "--host=0.0.0.0", "--port=3000" ]
    profiles:
      - all
      - summary

  nginx:
    image: nginx:latest
    restart: always
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conversation:/usr/share/nginx/html
    ports:
      - ${LOG_PORT}:80
    command: [ "nginx", "-g", "daemon off;" ]
    profiles:
      - all
      - chat
      - recommendation
      - summary
