services:
  chat:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./srcs:/app/srcs
      - ./conversation:/app/conversation
    ports:
      - ${PORT}:3000
    command: ["uvicorn", "srcs.main:app", "--reload", "--host=0.0.0.0", "--port=3000"]

  nginx:
    image: nginx:latest
    restart: always
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conversation:/usr/share/nginx/html
    ports:
      - ${LOG_PORT}:80
    command: ["nginx", "-g", "daemon off;"]